name: Cypress + k6 Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npm run cypress:run

      - name: Generate Cypress HTML Report
        run: |
          npx mochawesome-merge cypress/reports/mochawesome/*.json > merged-report.json
          npx marge merged-report.json --reportDir cypress/reports/html

      - name: Upload Cypress HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/reports/html

  k6:
    name: k6 Performance Tests
    runs-on: ubuntu-latest
    needs: cypress

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install xk6 and Build k6 with Dashboard
        run: |
          go install go.k6.io/xk6/cmd/xk6@latest
          xk6 build --with github.com/grafana/xk6-dashboard@latest
          mv k6 ./k6-bin

      - name: Run k6 Performance Test and Generate HTML Report
        run: |
            mkdir -p k6-tests/reports
          ./k6-bin run --out dashboard --summary-export=k6-tests/reports/k6-dashboard.html k6-tests/performance.tests.js

      - name: List files in k6-tests/reports
        run: ls -al k6-tests/reports

      - name: Upload k6 Dashboard HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: k6-dashboard-html
          path: k6-tests/reports/k6-dashboard.html